// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp-1BrIg2x1J2_a0JT7u8ZzWTOovNfcjo',
    appId: '1:1004752001258:web:b9cb19f621de688ea8df93',
    messagingSenderId: '1004752001258',
    projectId: 'biomaj-pro',
    authDomain: 'biomaj-pro.firebaseapp.com',
    storageBucket: 'biomaj-pro.firebasestorage.app',
    measurementId: 'G-H77PKVH8EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-nxZOJONTuMW0g8ltaH5km9pppyLxELg',
    appId: '1:1004752001258:android:b45d0bfcdbf43e89a8df93',
    messagingSenderId: '1004752001258',
    projectId: 'biomaj-pro',
    storageBucket: 'biomaj-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDamodLmE3urznTLn_fBWMuoIzPqbR1M2o',
    appId: '1:1004752001258:ios:ada9de6fa801b143a8df93',
    messagingSenderId: '1004752001258',
    projectId: 'biomaj-pro',
    storageBucket: 'biomaj-pro.firebasestorage.app',
    iosBundleId: 'com.example.testpjt',
  );
}
